#:import IconButton widgets.buttons.IconButton
#:import RoundedButton widgets.buttons.RoundedButton
#:import Text widgets.labels.Text

<WheyScreen>:
    canvas.before:
        Color:
            rgba: app.colors.white
        Rectangle:
            pos: self.pos
            size: self.size
    RelativeLayout:
        BoxLayout:
            orientation: 'vertical'
            BoxLayout:
                size_hint_y: .7
                canvas.before:
                    Color:
                        rgba: [1,1,1,1]
                    Rectangle:
                        pos: self.pos
                        size: self.size
                        source: root.source
            BoxLayout:
                size_hint_y: .3
        BoxLayout:
            orientation: 'vertical'
            AnchorLayout:
                size_hint_y: .6
                padding: dp(12)
                anchor_x: 'left'
                anchor_y: 'top'
                BoxLayout:
                    padding: dp(8)
                    size_hint: [None, None]
                    size: [dp(32), dp(32)]
                    canvas.before:
                        Color:
                            rgba: app.colors.white
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [dp(8)]
                    IconButton:
                        source: 'assets/icons/back.png'
                        on_release: app.root.ids.scrn_mngr.current = 'scrn_home'
            BoxLayout:
                size_hint_y: .4
                padding: dp(12)
                spacing: dp(8)
                orientation: 'vertical'
                canvas.before:
                    Color:
                        rgba: [.6, .6, .6, .1]
                    RoundedRectangle:
                        pos: [self.pos[0], self.pos[1]+dp(2)]
                        size: self.size
                        radius: [self.height/8, self.height/8, 0, 0]
                    Color:
                        rgba: app.colors.white
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [self.height/8, self.height/8, 0, 0]
                BoxLayout:
                    size_hint_y: None
                    height: dp(32)
                    Text:
                        text: root.name
                        font_name: app.fonts.heading
                        font_size: app.fonts.size.h2
                        color: app.colors.secondary
                    AnchorLayout:
                        size_hint_x: None
                        width: self.height
                        padding: dp(2)
                        anchor_x: 'right'
                        IconButton:
                            source: 'assets/icons/fav-filled.png'
                BoxLayout:
                    size_hint_y: None
                    height: dp(15)
                    Text:
                        text: '100% Whey Protein Powder, Double Rich Chocolate'
                        font_name: app.fonts.subheading
                        font_size: app.fonts.size.h6
                        color: app.colors.grey
                    Widget:
                        size_hint_x: None
                        width: self.height
                BoxLayout:
                    size_hint_y: None
                    height: dp(15)
                    BoxLayout:
                        size_hint_x: .5
                        id: stars
                        IconButton:
                            source: 'assets/icons/star-filled.png'
                            size_hint_x: None
                            width: self.height
                        IconButton:
                            source: 'assets/icons/star-filled.png'
                            size_hint_x: None
                            width: self.height
                        IconButton:
                            source: 'assets/icons/star-filled.png'
                            size_hint_x: None
                            width: self.height
                        IconButton:
                            source: 'assets/icons/star-filled.png'
                            size_hint_x: None
                            width: self.height
                        IconButton:
                            source: 'assets/icons/star-outline.png'
                            size_hint_x: None
                            width: self.height
                    Widget:
                        size_hint_x: None
                        width: self.height
                ScrollView:
                    BoxLayout:
                        anchor_y: 'top'
                        GridLayout:
                            cols: 1
                            padding: 10
                            Label:
                                text: "• Each serving of the world's best-selling whey protein powder provides 24 grams of high-quality whey protein primarily from Whey Protein Isolate, which has had excess carbohydrates, fat, and lactose ‘isolated’ out using sophisticated filtering technologies. The powder is also instantized for easy mixing using just a glass and spoon. With more than 20 different flavors – including naturally flavored options – there’s no doubt this is the Optimum Nutrition Gold Standard 100% Whey Protein."
                                size: self.texture_size
                                size_hint_y: None
                                valign: 'top'
                                halign: 'left'
                                text_size: [self.width-20, None]
                                font_name: app.fonts.body
                                font_size: app.fonts.size.h5
                                color: app.colors.secondary
                            Label:
                                text: "• Mix about one scoop of the powder into 6 to 8 fluid ounces of cold water, milk or other beverage. Stir, shake or blend until dissolved. For best results, mix up your shake 30 to 60 minutes after your workout or use as an anytime snack in your balanced diet."
                                size: self.texture_size
                                size_hint_y: None
                                valign: 'top'
                                halign: 'left'
                                text_size: [self.width-20, None]
                                font_name: app.fonts.body
                                font_size: app.fonts.size.h5
                                color: app.colors.secondary
                            Label:
                                text: "• For healthy adults, consume enough protein to meet your daily protein requirements with a combination of high protein foods and protein supplements throughout the day as part of a balanced diet and exercise program."
                                size: self.texture_size
                                size_hint_y: None
                                valign: 'top'
                                halign: 'left'
                                text_size: [self.width-20, None]
                                font_name: app.fonts.body
                                font_size: app.fonts.size.h5
                                color: app.colors.secondary
                            Label:
                                text: "• 24 Grams of Protein per Serving to Help Build and Maintain Muscle³"
                                size: self.texture_size
                                size_hint_y: None
                                valign: 'top'
                                halign: 'left'
                                text_size: [self.width-20, None]
                                font_name: app.fonts.body
                                font_size: app.fonts.size.h5
                                color: app.colors.secondary
                            Label:
                                text: "• 5.5 Grams of Naturally Occurring BCAAs per Serving to Support Endurance and Recovery"
                                size: self.texture_size
                                size_hint_y: None
                                valign: 'top'
                                halign: 'left'
                                text_size: [self.width-20, None]
                                font_name: app.fonts.body
                                font_size: app.fonts.size.h5
                                color: app.colors.secondary
                            Label:
                                text: "• 3-4G CARBS, 1-3G SUGAR, AND 1-1.5G FAT, GLUTEN FREE, No Sucralose in Double Rich Chocolate Flavor"
                                size: self.texture_size
                                size_hint_y: None
                                valign: 'top'
                                halign: 'left'
                                text_size: [self.width-20, None]
                                font_name: app.fonts.body
                                font_size: app.fonts.size.h5
                                color: app.colors.secondary
                            Label:
                                text: "• ANY-TIME FORMULA – great before or after exercise, between meals, with a meal, or any time of day where you need extra protein in your nutrition"
                                size: self.texture_size
                                size_hint_y: None
                                valign: 'top'
                                halign: 'left'
                                text_size: [self.width-20, None]
                                font_name: app.fonts.body
                                font_size: app.fonts.size.h5
                                color: app.colors.secondary
                            Label:
                                text: "• Most Awarded, Best-Selling Whey Protein Powder On The Planet"
                                size: self.texture_size
                                size_hint_y: None
                                valign: 'top'
                                halign: 'left'
                                text_size: [self.width-20, None]
                                font_name: app.fonts.body
                                font_size: app.fonts.size.h5
                                color: app.colors.secondary
        
        