#:import WheyScreen screens.wheypro.WheyScreen
#:import Home screens.home.Home
<MainWindow>:
    orientation: 'vertical'
    canvas.before:
        Color:
            rgba: rgba('#ffffff')
        Rectangle:
            pos: self.pos
            size: self.size
    ScreenManager:
        id: scrn_mngr
        Screen:
            name: 'scrn_home'
            Home:
                id: home
        Screen:
            name: 'scrn_whey'
            WheyScreen:
                id: whey_screen